name: 'CEFIM 2023 - CI'
on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutttt
        uses: actions/checkout@v3

