name: 'CEFIM 2023 - CI'
on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoutttt
        uses: actions/checkout@v3
      - name: Display hello world
        run: echo 'Hello world'
      - name: Display Node version
        run: touch truc.txt
      - name: Affichage
        run: ls
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Affichage
        run: ls
